name:                crudApp
version:             0.1.0.0
github:              "githubuser/crudApp"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/crudApp#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- esqueleto
- postgresql-simple
- persistent
- persistent-postgresql
- persistent-template
- monad-logger
- text
- time
- jwt
- servant-auth-server
- bytestring
- uuid



ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  crudApp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - crudApp

tests:
  crudApp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - crudApp
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
